# NumPy基础

## 1-1 NumPy数组的构造

In [1]:
import numpy as np

from base.practice3 import total

#构造一维数组
np.array([1,2,3])

array([1, 2, 3])

In [3]:
#等差数列
np.linspace(1,5,5)
np.arange(1,5,1)

array([1, 2, 3, 4])

#### 1.特殊矩阵

In [6]:
#特殊矩阵-全零矩阵
np.zeros((2,3,4))
#特殊矩阵-全一矩阵
np.ones((2,3,4))
#填充函数np.full()
np_input = [[1,2],[3,4],[5,6]]
np.full((2,3,3,2),np_input) # 广播

array([[[[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]]],


       [[[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]]]])

In [7]:
#生成与给定数组相同的特殊矩阵-全零矩阵
arr = [[1,2],[3,4],[5,6]]
np.zeros_like(arr)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [8]:
#生成与给定数组相同的特殊矩阵-全一矩阵
np.ones_like(arr)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [9]:
#生成与给定数组相同的特殊矩阵-填充矩阵
np.full_like(arr,[90,80])

array([[90, 80],
       [90, 80],
       [90, 80]])

In [11]:
#单位矩阵
np.eye(3)
np.eye(4,k=1) #偏移距离->向上偏移k个单位

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

#### 1.2随机数组

In [15]:
# uniform() - 均匀分布的随机数组
np.random.uniform(-1,2,3) # 一维
np.random.uniform(-1,2,(2,3)) # 二维

# 特殊：rand() - 服从U[0,1]的均匀分布的数组
np.random.rand(3) # 一维
np.random.rand(3,3) # 二维

array([[0.76244209, 0.82514542, 0.51088678],
       [0.55553955, 0.21382974, 0.74167077],
       [0.08821924, 0.43819168, 0.53479325]])

In [18]:
# normal() - 生成N[μ，σ]正态分布的数组
mu,sigma = 3,2.5
np.random.normal(mu,sigma,3) # 一维
np.random.normal(mu,sigma,(3,3)) # 二维

# 特殊：randn() - 生成服从N[0，1]标准正态分布的数组
np.random.randn(3) # 一维
np.random.randn(3,3) # 二维

array([[-0.56512127, -0.06742007,  0.91524577],
       [ 2.39903855,  0.39219039, -0.21294663],
       [ 0.83829005, -0.66253364,  1.5468948 ]])

In [19]:
# randint() - 生成在给定整数范围内的呈离散均匀分布的数组，high对应的数值不包括在内。
low,high,size = 1,10,(2,3)
np.random.randint(low,high,size)

array([[3, 2, 6],
       [9, 6, 6]])

In [23]:
# choice() - 以一定概率和方式抽取元素，当不指定概率时为等概率抽样
my_list = ['a','b','c','d']
np.random.choice(
    my_list,
    3,
    replace= False, # 不放回
    p=[0.1,0.7,0.1,0.1] # 指定概率
)
np.random.choice(my_list,(3,3)) # 此时不能指定replace = False

#当返回的元素个数与原列表的元素个数相同时，不放回抽样等价于permutation()，即打散原列表。
np.random.permutation(my_list)

array(['b', 'c', 'd', 'a'], dtype='<U1')

In [24]:
# 随机种子 ->固定随机数的输出结果
np.random.seed(0)
np.random.rand() # 结果固定为0.5488135039273248

0.5488135039273248

## 1-2NumPy数组的变形

### 1.由元素组织方式变化导致的变形

In [26]:
# 维度交换方法：transpose()和T操作
carbon = np.random.rand(360,180,3)
res = carbon.transpose(2,0,1) # 将最后一个维度前置
res.shape

(3, 360, 180)

In [28]:
# T操作
res = carbon.T # 特殊的transpose，将元素逆向变换
res.shape
# 特殊：矩阵转置 (行变列，列变行)
my_matrix = np.array([[2,3],[4,5]])
my_matrix.T

array([[2, 4],
       [3, 5]])

In [32]:
# 重构维度：reshape()
my_matrix02 = np.arange(8)
my_matrix02.reshape(2,4,order="C") # 按行为顺序进行重构
my_matrix02.reshape(2,4,order="F") # 按列为顺序进行重构

#改变读取顺序
my_matrix02.reshape(2,4,order="C").reshape(8,order="F") # 按列为顺序进行读取

# -1占位：reshape()允许有一个维度存在空缺，只需填充-1。
my_matrix02.reshape(2,2,-1)
my_matrix02.reshape(2,-1,2)
my_matrix02.reshape(-1,2,2)

array([0, 4, 1, 5, 2, 6, 3, 7])

In [34]:
# 特殊：多维度进行插入或者挤压维度,并且维度数为1
# expand_dims()插入维度
target = np.ones((2,2)) # 创建2x2的数组
expand_target = np.expand_dims(target,(0,2))  # 变形为1×2×1×2
expand_target.shape

# squeeze()挤压数组
np.squeeze(expand_target,(0,2))

array([[1., 1.],
       [1., 1.]])

### 2.由合并或拆分导致的变形

In [35]:
# 合并：concatenate() & stack() - 在某一个维度上连接多个数组
# 创建一个具有实际含义的数组，维度为20×6××3，含义为年份（1981-2000），月份（1月-6月）与人口指标（出生率、死亡率和总人口数）

# stack()拼接后会产生新的维度
pop_man = np.random.rand(20,6,3) # 男性
pop_women = np.random.rand(20,6,3) # 女性
res = np.stack([pop_man,pop_women],axis=2)
res.shape

(20, 6, 2, 3)

In [37]:
# concatenate()是一种同质性或连续性拼接
pop_1_6 = np.random.rand(20,6,3) # 1-6月
pop_7_12 = np.random.rand(20,6,3) # 7-12月
res = np.concatenate([pop_1_6,pop_7_12],axis=1) # 将月份扩展到12个月
res.shape

(20, 12, 3)

In [38]:
# 将两组月份割裂看待，而不是连续
res = np.stack([pop_1_6,pop_7_12],axis=1) # 表示在月份前加入上半年和下半年的维度
res.shape

(20, 2, 6, 3)

In [43]:
# 分割函数：split()
# indices_or_sections为整数则表明对某个维度的维数均匀分割
res = np.split(pop_1_6,indices_or_sections=3,axis=1)
for i in res:
    print(i.shape)

(20, 2, 3)
(20, 2, 3)
(20, 2, 3)
(20, 1, 3)
(20, 2, 3)
(20, 3, 3)


In [44]:
# 分割函数：split()
# indices_or_sections为数组则表明对某个维度的维数分割点数 （不均匀分割）
res = np.split(pop_1_6,indices_or_sections=[1,4],axis=1)
for i in res:
    print(i.shape)

(20, 1, 3)
(20, 3, 3)
(20, 2, 3)


In [47]:
# 练一练：split()函数从功能上更类似于concatenate()的逆操作还是stack()的逆操作？请说明理由。
# 更像concatenate()的逆操作。理由如下：concatenate不会产生新维度
arr = np.random.rand(10,20,30)
new_arr = np.concatenate(np.split(arr,indices_or_sections=5,axis=1),axis=1)
(arr == new_arr).all()

np.True_

In [7]:
# 重复函数repeat()
a = np.arange(3)
np.repeat(a,repeats=2)
np.repeat(a,repeats=a+1)

array([0, 1, 1, 2, 2, 2])

In [10]:
b = [[1,2],[3,4]]
np.repeat(b,repeats=[3,4],axis=0)

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4],
       [3, 4]])

In [12]:
# 练一练
#使用repeat函数分别构造两个10×10的数组，
# 第一个数组要求第i行的元素值都为i，第二个数组要求第i列的元素值都为i。
np.repeat(np.arange(10).reshape(10,1),repeats=10,axis=1)
np.repeat(np.arange(10).reshape(1, 10), repeats=10, axis=0)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

## 1-3.NumPy数组的切片

In [15]:
# 切片操作
target = np.arange(24).reshape(4,2,3)
target[0:3,:,1:3]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]],

       [[13, 14],
        [16, 17]]])

In [16]:
# 花式索引（用整数列表按“点对点”取值）
target[[0,1],[0,1],[0,1]]

array([ 0, 10])

In [19]:
#用布尔值进行切片
target[[True,False,True,False], : ,:]

(2, 2, 3)

In [21]:
# 对于连续出现在最后的几个：可以省略
target[[True,False,True,False]].shape
# 对于连续出现在最前面的几个：可以用...简写
target[:,:,0::2].shape == target[...,0::2].shape

True

In [22]:
# np.newaxis：给原数组增加一个维度
target[:,np.newaxis,np.newaxis].shape

(4, 1, 1, 2, 3)

## 4.广播机制

##### 广播机制是 NumPy的重要机制，熟练地使用广播能够极大地提高数据处理的效率。那么什么是广播？考虑这样一个场景：某个小卖铺共有3件商品，有5位顾客前来消费，现在利用数组A记录顾客购买的商品件数，这里设第一维是顾客，第二维是商品。另外，我们还知道小卖铺每一件商品的单价，用长度为3的一维数组表示。超市的营业员想要每位顾客在**每件商品上的消费金额数组**。

In [28]:
piece = np.random.randint(0,5,(5,3))
price = np.random.uniform(10,100,3)
price = price.round(2)

res = np.array([i * price for i in piece])
res

array([[ 10.99,   0.  ,   0.  ],
       [ 32.97,  87.69,  79.04],
       [  0.  ,   0.  ,  79.04],
       [ 21.98,   0.  ,   0.  ],
       [ 10.99,   0.  , 237.12]])

In [29]:
piece * price

array([[ 10.99,   0.  ,   0.  ],
       [ 32.97,  87.69,  79.04],
       [  0.  ,   0.  ,  79.04],
       [ 21.98,   0.  ,   0.  ],
       [ 10.99,   0.  , 237.12]])

In [35]:
piece = piece.T
piece * price.reshape((3,1))

array([[[[[[ 10.99,   0.  ,   0.  ],
           [ 32.97,  10.99,  10.99],
           [  0.  ,   0.  ,  10.99],
           [ 21.98,   0.  ,   0.  ],
           [ 10.99,   0.  ,  32.97]],

          [[ 87.69,   0.  ,   0.  ],
           [263.07,  87.69,  87.69],
           [  0.  ,   0.  ,  87.69],
           [175.38,   0.  ,   0.  ],
           [ 87.69,   0.  , 263.07]],

          [[ 79.04,   0.  ,   0.  ],
           [237.12,  79.04,  79.04],
           [  0.  ,   0.  ,  79.04],
           [158.08,   0.  ,   0.  ],
           [ 79.04,   0.  , 237.12]]]]]])

## 5.常用函数

#### 1.计算函数

In [13]:
import numpy as np
school = np.random.randint(20,40,24).reshape(2,3,4) # 维度分别代表学校、年级、班级
school.sum(axis=(1,2)) # 压缩年级、班级

# 练一练📝
# 给出按年级统计学生总人数的方案，即返回数组的包含3个元素，
# 分别为各年级中所有学校和班级的学生人数之和。
school.sum(axis=(0,2))

#计算各学校所有班级中最大的学生总数
school.max(axis=(1,2))

# 计算中位数以及分位数
np.median(school,axis=-1) #计算所有学校所有年纪的中位数
np.quantile(school,axis=-1,q=0.5) # 参数q代表多少分位数

school = school.astype("float")
school[0][0][0] = np.nan
school.max(axis = (1,2))

array([nan, 39.])

In [15]:
# 相关性函数
target1 = [1,3,5,9]
target2 = [1,5,3,-9]
np.cov(target1,target2)

array([[ 11.66666667, -16.66666667],
       [-16.66666667,  38.66666667]])

In [16]:
np.corrcoef(target1,target2)

array([[ 1.        , -0.78470603],
       [-0.78470603,  1.        ]])

In [18]:
# ufunc函数
# 计算绝对值
target3 = np.arange(-4,5).reshape(3,-1)
np.abs(target3)

array([[4, 3, 2],
       [1, 0, 1],
       [2, 3, 4]])

In [20]:
np.power(target3,2)

array([[16,  9,  4],
       [ 1,  0,  1],
       [ 4,  9, 16]])

In [21]:
# 对数换底公式
two,ten = 2 * np.ones(2) , 10 * np.ones(2)
np.abs(np.log(ten) / np.log(two) - np.log2(ten) < 1e-15)

array([ True,  True])

In [22]:
# 练一练:现给定一个二维数组，请对其进行逐行Softmax归一化，且不得使用for循环。
arr = np.random.rand(4,4)
exp_arr = np.exp(arr)
res = exp_arr / np.sum(exp_arr)
res

array([[0.07394391, 0.05086955, 0.03716862, 0.05977688],
       [0.05912378, 0.05299893, 0.07281245, 0.08134844],
       [0.04243471, 0.05260419, 0.04372774, 0.06871847],
       [0.06633119, 0.09895149, 0.07369024, 0.0654994 ]])

#### 2.逻辑函数

In [24]:
# all()函数
salary = np.array([[9000,13000],[11000,12000]]) # 公司的两个部门的工资
(salary>10000).all(axis=1)

array([False,  True])

In [31]:
# any()函数
salary = np.array([[9000,13000],[11000,12000]])
(salary>10000).any(axis=1)

array([ True,  True])

In [23]:
# 练一练 逻辑运算符的优先顺序是怎样的？其左右的数组能够被广播吗？请构造例子说明。
a = np.array([8,10,12,15,9])

# 逻辑运算符&
print((a > 10) & (a < 14))

# 逻辑运算符~
print(~(a > 10))

#广播
row = np.array([9000, 13000, 11000])
col = np.array([[1], [0], [1]])

mask_row = row > 10000
mask_col = col.astype('bool')

print(mask_row & mask_col)

[False False  True False False]
[ True  True False False  True]
[[False  True  True]
 [False False False]
 [False  True  True]]


In [26]:
# 练一练：给定一个维度为m×n的整数数组，请返回一个元素全为0或1的同维度数组，
# 且满足元素取1当且仅当该位置在原数组中的对应元素是原数组中同行元素的最大值。
import numpy as np

def row_max_mask(arr:np.ndarray) ->np.ndarray:
    """ 计算每行最大值，并创建0或1矩阵"""
    row_max = arr.max(axis=1,keepdims=True)
    return  (arr == row_max).astype('int')

#创建数组验证函数
arr = np.random.randint(1,10,12).reshape(3,4)
row_max = arr.max(axis=1,keepdims=True)
np.where(arr == row_max,1,0)

# print(arr)
# print(row_max_mask(arr))

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [1, 0, 1, 1]])

In [39]:
# 逻辑运算符的运用
my_array = np.random.rand(100,3)

condition1 =(~(my_array.sum(1)>1.5))
condition2 = (my_array[:,0]>0.5)&(my_array[:,2]>0.5)
res = my_array[condition1|condition2]

#验证
((res.sum(1)<1.5)|(res[:,[0,2]]>0.5).all(1)).all()


np.True_

In [10]:
# 练一练
new_array = np.random.rand(1000,3)
arr = new_array.round()
arr_1 = arr[arr.sum(1)<=1]
arr_2 = arr[~arr.all(1)]
arr_3 = arr[(arr.any(1))&(~arr.all(1))]
arr_3


array([[0., 0., 1.],
       [1., 1., 0.],
       [0., 1., 1.],
       ...,
       [1., 1., 0.],
       [0., 1., 0.],
       [0., 1., 1.]], shape=(743, 3))

In [21]:
# 练一练：np.clip(array, min, max)是一种截断函数，
# 对于数组中超过max的值会被截断为max，数组中不足min的值会被截断为min。
# 请用np.where()实现这个函数。

arr = np.array([1,2,2,3,4,4,5])
res = np.where(arr<=4,arr,4)
res = np.where(res>=2,res,2)
res

array([2, 2, 2, 3, 4, 4, 4])

In [22]:
# 练一练：在上面这个例子中，nonzero()的输入a是1维数组，通过a[np.nonzero(a)]能够取出数组中所有的非零元素值。
# 事实上，nonzero()函数也能够以高维数组作为参数传入，此时其返回值代表了什么含义？a[np.nonzero(a)]仍然能够选出数组中所有的非零元素值吗？请解释理由。

# 此时返回值是所有非零元素的坐标，可以选出所有非零元素值。
arr = np.array([[2,3,0,4],[1,0,3,-1]])
row,col = np.nonzero(arr) # 行和列
arr[row,col]

array([ 2,  3,  4,  1,  3, -1])

## 1.3习题

In [18]:
# 1.用列表推导式实现矩阵乘法
A = [[0, 1, 2],
     [3, 4, 5]]

B = [[0, 1],
     [2, 3],
     [4, 5]]

[
    [sum(a*b for a,b in zip(row,col))
     for col in zip(*B)]
    for row in A
]

[[10, 13], [28, 40]]

In [19]:
# 计算卡方统计量
np.random.seed(0)
A = np.random.randint(10,20,(8,5))

row_sums = A.sum(axis=1,keepdims=True)
col_sums = A.sum(axis=0,keepdims=True)
total = A.sum()

B = (row_sums @ col_sums) / total
chi2 = ((A-B)**2 / B).sum()

print(chi2)

11.842696601945802


In [20]:
np.load("data_base/data/ch1/shop_sales/product_1.npy").shape

(20, 12)

## 综合练习：商店销量与单价

数据在 `data_base/data/ch1/`：
- `shop_sales/product_1.npy` ~ `product_200.npy`：每种商品 20 年 × 12 月的销量，形状 `(20, 12)`
- `increase_rate.npy`：200 种商品、240 个月的「相对上月涨幅」，形状 `(200, 240)`
- `unit_price.npy`：200 种商品在 **2015 年 1 月** 的单价，长度 200

### 题目 1：按季度汇总销量

一年 12 个月 → 4 个季度，每季度 3 个月。

思路：把 `(20, 12)` 看成 `(20, 4, 3)`，再对最后一维（季度内的 3 个月）求和，得到 `(20, 4)`。

In [35]:
# 简化版
path = "data_base/data/ch1/shop_sales/product_%d.npy"
sales = np.stack([np.load(path%i) for i in range(1,201)],axis=0)
print("销量数组 shape:", sales.shape)# 200类货品
res = sales.reshape(200,20,4,-1).sum((0,-1))
res

销量数组 shape: (200, 20, 12)


array([[3314912, 3314813, 3314344, 3314658],
       [3314965, 3314924, 3315155, 3315207],
       [3315169, 3315478, 3315121, 3314961],
       [3315252, 3314981, 3314839, 3314647],
       [3314999, 3315414, 3315242, 3314982],
       [3315122, 3315467, 3315675, 3315566],
       [3315401, 3315351, 3315523, 3314939],
       [3315361, 3315030, 3315198, 3315806],
       [3316498, 3316613, 3317404, 3318257],
       [3318885, 3319103, 3318957, 3318554],
       [3318289, 3318561, 3318590, 3318763],
       [3318894, 3318750, 3317905, 3317625],
       [3318514, 3318496, 3318169, 3318211],
       [3318139, 3317578, 3317787, 3317781],
       [3317914, 3316628, 3316036, 3315521],
       [3315071, 3315118, 3314998, 3314716],
       [3314095, 3314031, 3314157, 3315044],
       [3315246, 3314885, 3314810, 3315130],
       [3314823, 3314736, 3314844, 3314723],
       [3314876, 3314372, 3314352, 3314491]])

### 题目 2：每个月、各类商品销量的方差

「不同类别商品」之间的差异有多大？对 200 种商品求方差。

`sales` 形状是 `(200, 20, 12)`，在第 0 维（商品）上算 `var`，得到 `(20, 12)`。

In [36]:
# axis=0：沿着「200 种商品」这一维算方差，每个 (年, 月) 得到一个数
month_var = sales.var(axis=0)
print(month_var.shape)  # (20, 12)
month_var

(20, 12)


array([[6322587.50439999, 6321709.1144    , 6320260.2464    ,
        6318926.144775  , 6316562.6636    , 6317820.7275    ,
        6318444.110775  , 6319600.9676    , 6323584.503975  ,
        6323881.15      , 6323599.8484    , 6321360.9551    ],
       [6322783.9816    , 6321624.6775    , 6320604.342975  ,
        6322777.4719    , 6321340.874375  , 6322059.007975  ,
        6322778.634375  , 6325648.9664    , 6325607.4784    ,
        6325462.0936    , 6325821.793975  , 6320405.6824    ],
       [6319413.9       , 6320114.4631    , 6320579.389775  ,
        6319141.8779    , 6320468.3175    , 6322888.5111    ,
        6325633.749975  , 6326386.203975  , 6324899.488775  ,
        6325388.2175    , 6323068.9679    , 6325317.134775  ],
       [6323961.075775  , 6324016.41749999, 6321591.880975  ,
        6320000.378775  , 6321077.11937499, 6319211.428775  ,
        6317157.05999999, 6317268.47437499, 6319672.5176    ,
        6317069.465775  , 6318448.164375  , 6322420.435975  ],
    

### 题目 3：还原 2001-01 ~ 2020-12 的全部单价

核心关系只有一句：

$$\text{本月单价} = \text{上月单价} \times (1 + \text{本月涨幅})$$

已知 2015-01 的单价当「锚点」：往后连乘、往前连除，得到全部 240 个月，再整理成 `(20, 12, 200)`。

两种常见写法对比：

| | 全局累计比（我之前的） | 分段往前/往后（参考写法） |
|--|--|--|
| 思路 | 先算整段 `cumprod`，再除以锚点处的累计值 | 锚点右边单独往后乘，左边单独往前除 |
| 优点 | 公式统一、代码短 | 方向一眼能看懂，只算需要的区间 |
| 缺点 | 要先拼一列 `1`，语义稍绕 | 往前那段有 `::-1` 翻转，初看容易懵 |

下面是整合优化版：保留「分段」的清晰语义，变量名说人话。

In [37]:
rate = np.load("data_base/data/ch1/increase_rate.npy")  # (200, 240) 每月相对上月涨幅
base = np.load("data_base/data/ch1/unit_price.npy")     # (200,)     2015-01 单价（锚点）

# 月份下标：0=2001-01，168=2015-01，239=2020-12
n = (2015 - 2001) * 12  # 等价于 14 * 12
mult = 1.0 + rate         # 乘子：本月价 = 上月价 * mult[本月]

price = np.empty((200, 20 * 12))  # (商品, 240个月)
price[:, n] = base                # 先钉住锚点

# 往后（2015-02 ~ 2020-12）：从锚点出发连乘
# cumprod 后第 k 列 = mult[n+1] * mult[n+2] * ... * mult[n+1+k]
price[:, n + 1 :] = mult[:, n + 1 :].cumprod(axis=1) * base[:, None]

# 往前（2001-01 ~ 2014-12）：从锚点往回除 = 乘 1/mult
# 先把区间翻转，从近到远 cumprod，再翻转回来，对齐到月份 0..n-1
# rate[:, 0] 用不到：没有「更早一个月」可参照
inv = (1.0 / mult[:, 1 : n + 1])[:, ::-1].cumprod(axis=1)[:, ::-1]
price[:, :n] = inv * base[:, None]

# (商品,年,月) -> 题目要求的 (年,月,商品)
unit_prices = price.reshape(200, 20, 12).transpose(1, 2, 0)
print(unit_prices.shape)  # (20, 12, 200)
np.allclose(unit_prices[14, 0], base)  # 校验锚点月份

(20, 12, 200)


True

### 题目 4：每种商品「月销售额」最高的月份

月销售额 = 单价 × 销量。对每种商品在 240 个月里找最大值所在月份，输出形如 `"2008-05"`。

两种写法对比（结果相同）：

| | 我之前的 | 参考写法 |
|--|--|--|
| 对齐维度 | 把 `price` 转成 `(200,20,12)` 去乘销量 | 把销量转成 `(20,12,200)` 去乘 `price` |
| 摊平找最大 | `reshape(200, 240).argmax(1)`：一行一种商品 | `reshape(240, 200).argmax(0)`：一列一种商品 |
| 优点 | 「商品在第 0 维」和前面 `sales` 一致，好跟销量对读 | 一行写完更短；和第三题 `price` 形状直接相乘 |
| 缺点 | 稍多两行 | `transpose` + `argmax(0)` 要多想一步维度 |

整合版：沿用第三题的 `price` 形状直接相乘（更短），变量名说清楚，日期用 f-string。

In [ ]:
# sales/arr: (200,20,12)  单价 unit_prices/price: (20,12,200)
# 先把销量转成和单价一样的形状，相乘 = 每月销售额
revenue = sales.transpose(1, 2, 0) * unit_prices   # (20, 12, 200)

# 把「年×月」摊成 240 行，每种商品一列；沿时间轴找最大值下标
idx = revenue.reshape(-1, 200).argmax(axis=0)      # (200,) 取值 0~239

year = idx // 12 + 2001   # 第几个 12 月块 → 年份
month = idx % 12 + 1      # 块内余数 → 1~12 月

peak_months = [f"{y}-{m:02d}" for y, m in zip(year, month)]
peak_months[:5]  # 展示前 5 个