# NumPy基础

## 1-1 NumPy数组的构造

In [1]:
import numpy as np

#构造一维数组
np.array([1,2,3])

array([1, 2, 3])

In [3]:
#等差数列
np.linspace(1,5,5)
np.arange(1,5,1)

array([1, 2, 3, 4])

#### 1.特殊矩阵

In [6]:
#特殊矩阵-全零矩阵
np.zeros((2,3,4))
#特殊矩阵-全一矩阵
np.ones((2,3,4))
#填充函数np.full()
np_input = [[1,2],[3,4],[5,6]]
np.full((2,3,3,2),np_input) # 广播

array([[[[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]]],


       [[[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]],

        [[1, 2],
         [3, 4],
         [5, 6]]]])

In [7]:
#生成与给定数组相同的特殊矩阵-全零矩阵
arr = [[1,2],[3,4],[5,6]]
np.zeros_like(arr)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [8]:
#生成与给定数组相同的特殊矩阵-全一矩阵
np.ones_like(arr)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [9]:
#生成与给定数组相同的特殊矩阵-填充矩阵
np.full_like(arr,[90,80])

array([[90, 80],
       [90, 80],
       [90, 80]])

In [11]:
#单位矩阵
np.eye(3)
np.eye(4,k=1) #偏移距离->向上偏移k个单位

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

#### 1.2随机数组

In [15]:
# uniform() - 均匀分布的随机数组
np.random.uniform(-1,2,3) # 一维
np.random.uniform(-1,2,(2,3)) # 二维

# 特殊：rand() - 服从U[0,1]的均匀分布的数组
np.random.rand(3) # 一维
np.random.rand(3,3) # 二维

array([[0.76244209, 0.82514542, 0.51088678],
       [0.55553955, 0.21382974, 0.74167077],
       [0.08821924, 0.43819168, 0.53479325]])

In [18]:
# normal() - 生成N[μ，σ]正态分布的数组
mu,sigma = 3,2.5
np.random.normal(mu,sigma,3) # 一维
np.random.normal(mu,sigma,(3,3)) # 二维

# 特殊：randn() - 生成服从N[0，1]标准正态分布的数组
np.random.randn(3) # 一维
np.random.randn(3,3) # 二维

array([[-0.56512127, -0.06742007,  0.91524577],
       [ 2.39903855,  0.39219039, -0.21294663],
       [ 0.83829005, -0.66253364,  1.5468948 ]])

In [19]:
# randint() - 生成在给定整数范围内的呈离散均匀分布的数组，high对应的数值不包括在内。
low,high,size = 1,10,(2,3)
np.random.randint(low,high,size)

array([[3, 2, 6],
       [9, 6, 6]])

In [23]:
# choice() - 以一定概率和方式抽取元素，当不指定概率时为等概率抽样
my_list = ['a','b','c','d']
np.random.choice(
    my_list,
    3,
    replace= False, # 不放回
    p=[0.1,0.7,0.1,0.1] # 指定概率
)
np.random.choice(my_list,(3,3)) # 此时不能指定replace = False

#当返回的元素个数与原列表的元素个数相同时，不放回抽样等价于permutation()，即打散原列表。
np.random.permutation(my_list)

array(['b', 'c', 'd', 'a'], dtype='<U1')

In [24]:
# 随机种子 ->固定随机数的输出结果
np.random.seed(0)
np.random.rand() # 结果固定为0.5488135039273248

0.5488135039273248

## 1-2NumPy数组的变形

### 1.由元素组织方式变化导致的变形

In [26]:
# 维度交换方法：transpose()和T操作
carbon = np.random.rand(360,180,3)
res = carbon.transpose(2,0,1) # 将最后一个维度前置
res.shape

(3, 360, 180)

In [28]:
# T操作
res = carbon.T # 特殊的transpose，将元素逆向变换
res.shape
# 特殊：矩阵转置 (行变列，列变行)
my_matrix = np.array([[2,3],[4,5]])
my_matrix.T

array([[2, 4],
       [3, 5]])

In [32]:
# 重构维度：reshape()
my_matrix02 = np.arange(8)
my_matrix02.reshape(2,4,order="C") # 按行为顺序进行重构
my_matrix02.reshape(2,4,order="F") # 按列为顺序进行重构

#改变读取顺序
my_matrix02.reshape(2,4,order="C").reshape(8,order="F") # 按列为顺序进行读取

# -1占位：reshape()允许有一个维度存在空缺，只需填充-1。
my_matrix02.reshape(2,2,-1)
my_matrix02.reshape(2,-1,2)
my_matrix02.reshape(-1,2,2)

array([0, 4, 1, 5, 2, 6, 3, 7])

In [34]:
# 特殊：多维度进行插入或者挤压维度,并且维度数为1
# expand_dims()插入维度
target = np.ones((2,2)) # 创建2x2的数组
expand_target = np.expand_dims(target,(0,2))  # 变形为1×2×1×2
expand_target.shape

# squeeze()挤压数组
np.squeeze(expand_target,(0,2))

array([[1., 1.],
       [1., 1.]])

### 2.由合并或拆分导致的变形

In [35]:
# 合并：concatenate() & stack() - 在某一个维度上连接多个数组
# 创建一个具有实际含义的数组，维度为20×6××3，含义为年份（1981-2000），月份（1月-6月）与人口指标（出生率、死亡率和总人口数）

# stack()拼接后会产生新的维度
pop_man = np.random.rand(20,6,3) # 男性
pop_women = np.random.rand(20,6,3) # 女性
res = np.stack([pop_man,pop_women],axis=2)
res.shape

(20, 6, 2, 3)

In [37]:
# concatenate()是一种同质性或连续性拼接
pop_1_6 = np.random.rand(20,6,3) # 1-6月
pop_7_12 = np.random.rand(20,6,3) # 7-12月
res = np.concatenate([pop_1_6,pop_7_12],axis=1) # 将月份扩展到12个月
res.shape

(20, 12, 3)

In [38]:
# 将两组月份割裂看待，而不是连续
res = np.stack([pop_1_6,pop_7_12],axis=1) # 表示在月份前加入上半年和下半年的维度
res.shape

(20, 2, 6, 3)

In [43]:
# 分割函数：split()
# indices_or_sections为整数则表明对某个维度的维数均匀分割
res = np.split(pop_1_6,indices_or_sections=3,axis=1)
for i in res:
    print(i.shape)

(20, 2, 3)
(20, 2, 3)
(20, 2, 3)
(20, 1, 3)
(20, 2, 3)
(20, 3, 3)


In [44]:
# 分割函数：split()
# indices_or_sections为数组则表明对某个维度的维数分割点数 （不均匀分割）
res = np.split(pop_1_6,indices_or_sections=[1,4],axis=1)
for i in res:
    print(i.shape)

(20, 1, 3)
(20, 3, 3)
(20, 2, 3)


In [47]:
# 练一练：split()函数从功能上更类似于concatenate()的逆操作还是stack()的逆操作？请说明理由。
# 更像concatenate()的逆操作。理由如下：concatenate不会产生新维度
arr = np.random.rand(10,20,30)
new_arr = np.concatenate(np.split(arr,indices_or_sections=5,axis=1),axis=1)
(arr == new_arr).all()

np.True_

In [ ]:
# TODO:重复函数、数组的切片